### PR TITLE
fix(raft): fixes issues with concurrent snapshot writers

### LINKED ISSUE #20: Concurrent writes to Raft snapshot files creates invalid snapshots
**Expected behavior**

Snapshots replicated from the leader should be an exact copy of the leader's snapshot, and locally written snapshots should be readable.

**Actual behavior**

It is possible that we schedule compaction for index X (on the Raft state thread) while at the same time replicating the snapshot for index X from our leader (on the Raft thread context). Since both point to the same file, and the writer lock is on the `FileSnapshot` instance, they can both write to the same file. This is exacerbated by the fact that on the state thread, when taking a snapshot, we schedule completion for later, so locking the snapshot is asynchronous. 

**Steps to reproduce**

Our setup (though may be reproduceable with smaller setups):

- Cluster of 5 nodes
- 8 partitions
- Replication factor of 3

Add logging when before/after persisting an in memory snapshot, and logging as well when completing the snapshot in `RaftServiceManager#scheduleCompletion` right before `snapshot.complete()` is called.

Add logging in `PassiveRole` before/after `pendingSnapshot.commit()` in `PassiveRole#onInstall`.

Start cluster, run some load, and randomly kill the leaders to cause fail over. If the planets align, you will sometimes see the logging statements above interleaved showing that we access the same file from two different threads.

Symptoms caused by this are unreadable snapshots (e.g. [this issue](https://github.com/atomix/atomix/issues/1007) or [this](https://github.com/zeebe-io/zeebe/issues/2766), and [this](https://github.com/zeebe-io/zeebe/issues/2359)).

**Minimal yet complete reproducer code (or URL to code)**

None but if need be I can try to come up with one.

**Environment**

 - Atomix: 3.2.0 (master)
 - OS: Linux
 - JVM: Java 1.8.0_181

<sup>:warning:️ Please verify that your issue still occurs on the latest version of Atomix before reporting. 
The documentation is currently work-in-progress and is not yet complete.</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking in with the [Atomix Google Group](https://groups.google.com/forum/#!forum/atomixio)?*

### PR DESCRIPTION
**Pull request by npepinpe**
- file snapshots are now written to a temporary file and moved to a permanent deterministic location on completion from which they are read

closes #20

### CODE REVIEW

**Comment by npepinpe** [comment]
@menski I added you to get your opinion on if this would be mergeable

**Comment by npepinpe** [comment]
@deepthidevaki I'd like to brainstorm how we could write a test for this tomorrow

**Comment by npepinpe** [comment]
I added back in memory snapshots in the end since I figured that'll make our PR more likely to be merged. There's one little thing with that though, is it makes no sense to have the `Snapshot#complete` method throw an `Exception` in its signature...so the exception handling when calling `Snapshot#complete` is...meh, I'd like to challenge it.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java [hunk 1]
```diff
@@ -842,16 +857,15 @@ public void incrementOffset() {
     /**
      * Commits the snapshot to disk.
      */
-    public void commit() {
-      snapshot.persist().complete();
+    public void commit() throws Exception {
```
Comment (deepthidevaki) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java]: I think it's not necessary to declare exception here.

**Review by deepthidevaki — APPROVED** [review]
:+1: Just a minor comment. You can merge it.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java (hunk 1 above)
Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java]: Ah, yes, left over from when I had `complete` also throw an Exception. :see_no_evil:
