### PR TITLE
Don't commit non replicated entries upon reconnecting

### LINKED ISSUE #17: Uncommitted events can become committed without quorum
**Expected behavior**

When an isolated node rejoins a raft, it should not commit any entries that were not replicated to other nodes.

**Actual behavior**

When a node that is leader for a partition becomes isolated (i.e. network partition), it can have written events to its log that were not replicated and therefore not committed (but still present, as it will keep trying to append them to its unreachable followers).

When the other nodes keep replicating amongst themselves and compaction occurs, and the isolated node rejoins, it will receive an empty append request from the new leader (i.e. a heartbeat) which contains the new commit index, term, previous log index, and previous log term. The new commit index is definitely higher than the index of the uncommitted leftover entries, and if truncation occurred on the new leader, it's possible that the previous log term is 0.

When the append request has no entries to append, and the previous log term is 0, then the append request is not rejected and the follower blindly commits all entries up to the new commit index, therefore committing the leftover entries.

**Steps to reproduce**

It's a bit hard, but we could reliably reproduce it by stress testing our system and disconnecting one node from the others, then ensure one or more backups is taken on the remaining nodes before reconnecting the isolated node; leftover entries will be applied to the primitives. This is particularly noticeable for us since the state of our custom primitive is stored on disk.

**Minimal yet complete reproducer code (or URL to code)**

None yet, will try to come up with a test

**Environment**

 - Atomix: 3.2.0
 - OS: Linux
 - JVM: java version "1.8.0_181" HotSpot

<sup>:warning:️ Please verify that your issue still occurs on the latest version of Atomix before reporting. 
The documentation is currently work-in-progress and is not yet complete.</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking in with the [Atomix Google Group](https://groups.google.com/forum/#!forum/atomixio)?*

### PR DESCRIPTION
**Pull request by deepthidevaki**
* previous term is 0 only for the first entry in the log
 * if there is no previous entry in the log after compaction, use the existing snapshot as previous entry.
 * reset follower's next index when install response is success
 * reset log after receiving a snapshot from leader

closes #17

### CODE REVIEW

File: protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftContext.java [hunk 1]
```diff
@@ -526,10 +527,11 @@ public long getFirstCommitIndex() {
   /**
    * Sets the last applied index.
    *
-   * @param lastApplied the last applied index
+   * @param lastApplied the last applied index and the last applied term
    */
-  public void setLastApplied(long lastApplied) {
+  public void setLastApplied(long lastApplied, long lastAppliedTerm) {
     this.lastApplied = Math.max(this.lastApplied, lastApplied);
+    this.lastAppliedTerm = lastAppliedTerm;
```
Comment (npepinpe) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftContext.java]: I'm not sure what is the case where we get lower terms/index, but we should keep the `lastApplied` and `lastAppliedTerm` in sync, and this `Math.max` thing might mess that up. So if we change one we have to change both.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftServiceManager.java [hunk 2]
```diff
@@ -363,7 +363,7 @@ private void applyIndex(long index) {
         }
         CompletableFuture future = futures.remove(index);
         apply(entry).whenComplete((r, e) -> {
-          raft.setLastApplied(index);
+          raft.setLastApplied(index, entry.entry().term());
```
Comment (npepinpe) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftServiceManager.java]: Can we anyway extract this as a final local variable before the lambda? Or mark entry as final. Atm this is allowed because the variable is implicitly final (i.e. never set elsewhere), but let's make it explicit. Either on the entry or the term (I'd prefer the term imo).

File: protocols/raft/src/main/java/io/atomix/protocols/raft/protocol/InstallRequest.java [hunk 3]
```diff
@@ -209,6 +223,12 @@ public Builder withLeader(MemberId leader) {
       return this;
     }
 
+    public Builder withSnapshotTerm(long term) {
+      checkArgument(snapshotTerm >= 0, "snapshotTerm must be positive");
```
Comment (npepinpe) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/protocol/InstallRequest.java]: Should we require it to be `> 0` instead? Does a snapshot term of 0 make any sense? :thinking:

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java [hunk 4]
```diff
@@ -309,6 +325,10 @@ protected void resetMatchIndex(RaftMemberContext member, AppendResponse response
    */
   protected void resetNextIndex(RaftMemberContext member, AppendResponse response) {
     long nextIndex = response.lastLogIndex() + 1;
+    resetNextIndex(member, nextIndex);
```
Comment (npepinpe) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java:328]: We probably don't need this method anymore, right? If it's only used in one place then let's inline this call.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java [hunk 5]
```diff
@@ -146,57 +146,71 @@ protected boolean checkTerm(AppendRequest request, CompletableFuture<AppendRespo
...
-          log.debug("Rejected {}: Previous index ({}) is greater than the local log's last index ({})", request, request.prevLogIndex(), lastEntry.index());
-          return failAppend(lastEntry.index(), future);
+        return checkPreviousEntry(request, lastEntry.index(), lastEntry.entry().term(), future);
+      } else {
+        final Snapshot currentSnapshot = raft.getSnapshotStore().getCurrentSnapshot();
+        if (currentSnapshot != null) {
+          return checkPreviousEntry(request, currentSnapshot.index(), currentSnapshot.term(), future);
+        } else {
+          // If the previous log index is set and the last entry is null and there is no snapshot, fail the append.
+          if (request.prevLogIndex() > 0) {
```
Comment (npepinpe) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java:166]: Should we in general skip the whole method if `request.prevLogIndex() == 0`?

File: protocols/raft/src/test/java/io/atomix/protocols/raft/RaftTest.java [hunk 6]
```diff
@@ -1276,6 +1277,50 @@ public void testSnapshotSentOnDataLoss() throws Throwable {
...
+    MemberId leaderId = members.stream().filter(m -> servers.get(m.memberId()).isLeader()).findFirst().get().memberId();
+    servers.get(leaderId).compact().get(15_000, TimeUnit.MILLISECONDS);
+
+    final Snapshot currentSnapshot = storages.get(leaderId).openSnapshotStore().getCurrentSnapshot();
+    final long leaderTerm = servers.get(leaderId).getTerm();
+
+    assertEquals(currentSnapshot.term(), leaderTerm);
+
+    final RaftServer server = createServer(members.get(0).memberId());
+    server.join(memberIds).get(15_000, TimeUnit.MILLISECONDS);
```
Comment (npepinpe) [inline protocols/raft/src/test/java/io/atomix/protocols/raft/RaftTest.java:1320]: When `join` completes, we are guaranteed to have received the leader snapshot? Are we in a passive state until then because there were no events to apply?

**Review by npepinpe — CHANGES_REQUESTED** [review]
:+1: 

Some questions and change requests, if you want we can have a quick call to go over them

File: protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftContext.java (hunk 1 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftContext.java]: Yes.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/protocol/InstallRequest.java (hunk 3 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/protocol/InstallRequest.java]: Yes. it must be > 0

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java (hunk 4 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java:328]: ` resetNextIndex(member, nextIndex)` is also used in `handleInstallResponseOK`

Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java:328]: Ah, sorry, I meant this one, `resetNextIndex(RaftMemberContext member, AppendedResponse response)`

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java (hunk 5 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java:166]: if `prevLogIndex==0`, wouldn't `prevLogTerm==0`?

File: protocols/raft/src/test/java/io/atomix/protocols/raft/RaftTest.java (hunk 6 above)
Comment (deepthidevaki) [reply protocols/raft/src/test/java/io/atomix/protocols/raft/RaftTest.java:1320]: In this case since the sever is restarting, I assume join completes after receiving a snapshot.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java (hunk 5 above)
Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java:166]: True, should be.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java (hunk 4 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java:328]: It is used in both LeaderAppender and AbstractAppender in `handleAppendResponseOK` . Looks like duplicated logic :man_shrugging:

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java (hunk 5 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/PassiveRole.java:166]: So it is covered in the outer `if` block.

**Comment by deepthidevaki** [comment]
@npepinpe I have updated the PR.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java (hunk 4 above)
Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java:328]: Hm. Then let's leave it as is for now, they can always request it themselves.

**Review by npepinpe — APPROVED** [review]
:tada:

Thanks!

**Comment by npepinpe** [comment]
Once the test is fixed, just rebase and call bors :+1:
