### PR TITLE
chore(raft): fixes race condition when resetting heartbeat timer

### LINKED ISSUE #139: Possible race condition on missing/receive heartbeat
**Expected behavior**

It seems to happen that we received an heartbeat, but not take them correctly into account.

Found this in one of our benchmark logs:

```
I 2020-01-09T23:59:49.275323494Z 2020-01-09 23:59:49.274 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.108S (calculated from last 24 ms)
 
I 2020-01-09T23:59:49.499736594Z 2020-01-09 23:59:49.499 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-09T23:59:49.800301848Z 2020-01-09 23:59:49.800 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.182S (calculated from last 50 ms)
 
I 2020-01-09T23:59:50.000016295Z 2020-01-09 23:59:49.999 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-09T23:59:50.678282319Z 2020-01-09 23:59:50.677 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.894S (calculated from last 178 ms)
 
I 2020-01-09T23:59:50.764372637Z 2020-01-09 23:59:50.764 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-09T23:59:53.582299635Z 2020-01-09 23:59:53.581 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.331S (calculated from last 82 ms)
 
I 2020-01-09T23:59:53.702952056Z 2020-01-09 23:59:53.702 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from null in the last PT3.203S (calculated from last 117 ms)
 
I 2020-01-09T23:59:53.749794601Z 2020-01-09 23:59:53.749 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-09T23:59:54.568533954Z 2020-01-09 23:59:54.568 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.818S (calculated from last 67 ms)
 
I 2020-01-09T23:59:54.750650623Z 2020-01-09 23:59:54.750 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-09T23:59:57.010579991Z 2020-01-09 23:59:57.010 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.425S (calculated from last 9 ms)
 
I 2020-01-09T23:59:57.095574859Z 2020-01-09 23:59:57.095 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from null in the last PT2.595S (calculated from last 76 ms)
 
I 2020-01-09T23:59:57.249728092Z 2020-01-09 23:59:57.249 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-09T23:59:57.761577278Z 2020-01-09 23:59:57.761 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.261S (calculated from last 12 ms)
 
I 2020-01-09T23:59:58.000352220Z 2020-01-09 23:59:58.000 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-09T23:59:59.605256921Z 2020-01-09 23:59:59.604 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.603S (calculated from last 103 ms)
 
I 2020-01-09T23:59:59.750365277Z 2020-01-09 23:59:59.750 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:00.980679020Z 2020-01-10 00:00:00.972 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.952S (calculated from last 222 ms)
 
I 2020-01-10T00:00:01.001646521Z 2020-01-10 00:00:01.001 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:01.750355522Z 2020-01-10 00:00:01.750 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.997S (calculated from last 250 ms)
 
I 2020-01-10T00:00:01.758910586Z 2020-01-10 00:00:01.758 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:02.675925572Z 2020-01-10 00:00:02.675 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.174S (calculated from last 176 ms)
 
I 2020-01-10T00:00:02.751016025Z 2020-01-10 00:00:02.750 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:05.495051359Z 2020-01-10 00:00:05.494 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.995S (calculated from last 243 ms)
 
I 2020-01-10T00:00:05.501057447Z 2020-01-10 00:00:05.500 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:05.677012667Z 2020-01-10 00:00:05.676 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.927S (calculated from last 176 ms)
 
I 2020-01-10T00:00:05.750611656Z 2020-01-10 00:00:05.750 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:05.806964703Z 2020-01-10 00:00:05.806 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.307S (calculated from last 56 ms)
 
I 2020-01-10T00:00:06.000970709Z 2020-01-10 00:00:06.000 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:09.170896116Z 2020-01-10 00:00:09.170 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.42S (calculated from last 165 ms)
 
I 2020-01-10T00:00:09.249707860Z 2020-01-10 00:00:09.249 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:09.378557270Z 2020-01-10 00:00:09.378 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.126S (calculated from last 129 ms)
 
I 2020-01-10T00:00:09.501263678Z 2020-01-10 00:00:09.500 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:09.696203674Z 2020-01-10 00:00:09.695 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.195S (calculated from last 195 ms)
 
I 2020-01-10T00:00:09.750573115Z 2020-01-10 00:00:09.750 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:12.002408001Z 2020-01-10 00:00:12.002 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.996S (calculated from last 0 ms)
 
I 2020-01-10T00:00:12.249986700Z 2020-01-10 00:00:12.249 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:13.578942131Z 2020-01-10 00:00:13.578 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.329S (calculated from last 55 ms)
 
I 2020-01-10T00:00:13.754659403Z 2020-01-10 00:00:13.754 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:14.025485270Z 2020-01-10 00:00:14.025 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.524S (calculated from last 3 ms)
 
I 2020-01-10T00:00:14.251336930Z 2020-01-10 00:00:14.251 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:16.065193340Z 2020-01-10 00:00:16.064 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.541S (calculated from last 63 ms)
 
I 2020-01-10T00:00:16.249968588Z 2020-01-10 00:00:16.249 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:16.279873292Z 2020-01-10 00:00:16.279 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.278S (calculated from last 30 ms)
 
I 2020-01-10T00:00:16.500969496Z 2020-01-10 00:00:16.500 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:17.308971618Z 2020-01-10 00:00:17.308 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.287S (calculated from last 55 ms)
 
I 2020-01-10T00:00:17.501061536Z 2020-01-10 00:00:17.500 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:19.654194700Z 2020-01-10 00:00:19.653 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.652S (calculated from last 153 ms)
 
I 2020-01-10T00:00:19.749778847Z 2020-01-10 00:00:19.749 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:20.693071200Z 2020-01-10 00:00:20.692 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.443S (calculated from last 174 ms)
 
I 2020-01-10T00:00:20.754607008Z 2020-01-10 00:00:20.754 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:20.833694944Z 2020-01-10 00:00:20.833 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.58S (calculated from last 79 ms)
 
I 2020-01-10T00:00:20.999712015Z 2020-01-10 00:00:20.999 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:22.005007790Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -3 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:22.086768617Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -23 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:22.449291338Z 2020-01-10 00:00:22.449 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.948S (calculated from last 62 ms)
 
I 2020-01-10T00:00:22.484478501Z 2020-01-10 00:00:22.484 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:22.836749926Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -6 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:23.166669832Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -2 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:24.141704300Z java.util.concurrent.TimeoutException: Request timed out after PT1M
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:132) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestWithRetry$0(AtomixClientTransportAdapter.java:61) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 
I 2020-01-10T00:00:24.237774352Z java.util.concurrent.TimeoutException: Request timed out after PT1M
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:132) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestWithRetry$0(AtomixClientTransportAdapter.java:61) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 
I 2020-01-10T00:00:24.965991973Z 2020-01-10 00:00:24.965 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.447S (calculated from last 21 ms)
 
I 2020-01-10T00:00:24.982820509Z 2020-01-10 00:00:24.982 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:25.044845646Z 2020-01-10 00:00:25.044 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.29S (calculated from last 3 ms)
 
I 2020-01-10T00:00:25.063032298Z 2020-01-10 00:00:25.062 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:26.949111538Z 2020-01-10 00:00:26.948 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.562S (calculated from last 15 ms)
 
I 2020-01-10T00:00:26.952159541Z 2020-01-10 00:00:26.951 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:27.845805227Z 2020-01-10 00:00:27.845 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.901S (calculated from last 12 ms)
 
I 2020-01-10T00:00:27.848406320Z 2020-01-10 00:00:27.848 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:29.060667956Z 2020-01-10 00:00:29.060 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.019S (calculated from last 2 ms)
 
I 2020-01-10T00:00:29.071865432Z 2020-01-10 00:00:29.071 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:31.461453555Z 2020-01-10 00:00:31.461 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.627S (calculated from last 14 ms)
 
I 2020-01-10T00:00:31.463799282Z 2020-01-10 00:00:31.463 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:31.670752203Z 2020-01-10 00:00:31.670 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.737S (calculated from last 5 ms)
 
I 2020-01-10T00:00:31.680070863Z 2020-01-10 00:00:31.679 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:33.142970337Z 2020-01-10 00:00:33.142 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.084S (calculated from last 10 ms)
 
I 2020-01-10T00:00:33.230679899Z 2020-01-10 00:00:33.230 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:33.315998102Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -8 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:34.866249908Z 2020-01-10 00:00:34.865 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.418S (calculated from last 3 ms)
 
I 2020-01-10T00:00:34.876478777Z 2020-01-10 00:00:34.876 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:34.968191820Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -1 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:35.033597884Z 2020-01-10 00:00:35.033 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.367S (calculated from last 8 ms)
 
I 2020-01-10T00:00:35.044443324Z 2020-01-10 00:00:35.044 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:37.256219806Z java.util.concurrent.TimeoutException: Request timed out after PT1M
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:132) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestWithRetry$0(AtomixClientTransportAdapter.java:61) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 
I 2020-01-10T00:00:37.317654931Z 2020-01-10 00:00:37.317 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.185S (calculated from last 13 ms)
 
I 2020-01-10T00:00:37.334361543Z 2020-01-10 00:00:37.332 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:38.169741504Z 2020-01-10 00:00:38.169 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.307S (calculated from last 11 ms)
 
I 2020-01-10T00:00:38.172045627Z 2020-01-10 00:00:38.171 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:38.632541065Z 2020-01-10 00:00:38.631 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.606S (calculated from last 10 ms)
 
I 2020-01-10T00:00:38.634957098Z 2020-01-10 00:00:38.634 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:39.063862812Z java.util.concurrent.TimeoutException: Request timed out after PT1M
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:132) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestWithRetry$0(AtomixClientTransportAdapter.java:61) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 
I 2020-01-10T00:00:40.021067390Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -1 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:40.888535205Z 2020-01-10 00:00:40.888 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.584S (calculated from last 12 ms)
 
I 2020-01-10T00:00:40.892824761Z 2020-01-10 00:00:40.892 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:41.292761781Z 2020-01-10 00:00:41.292 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.134S (calculated from last 8 ms)
 
I 2020-01-10T00:00:41.297002025Z 2020-01-10 00:00:41.296 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:41.564730868Z 2020-01-10 00:00:41.564 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.943S (calculated from last 1 ms)
 
I 2020-01-10T00:00:41.576736665Z 2020-01-10 00:00:41.576 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:44.298854006Z 2020-01-10 00:00:44.298 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.422S (calculated from last 13 ms)
 
I 2020-01-10T00:00:44.301182457Z 2020-01-10 00:00:44.300 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:45.790755Z 2020-01-10 00:00:45.790 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.506S (calculated from last 6 ms)
 
I 2020-01-10T00:00:45.809113667Z 2020-01-10 00:00:45.808 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:46.006385344Z 2020-01-10 00:00:46.006 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.442S (calculated from last 4 ms)
 
I 2020-01-10T00:00:46.016515091Z 2020-01-10 00:00:46.016 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:47.727639549Z 2020-01-10 00:00:47.727 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.442S (calculated from last 9 ms)
 
I 2020-01-10T00:00:47.730616927Z 2020-01-10 00:00:47.730 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:48.632879397Z 2020-01-10 00:00:48.632 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.631S (calculated from last 12 ms)
 
I 2020-01-10T00:00:48.635097153Z 2020-01-10 00:00:48.634 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:48.947385226Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -4 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:00:50.108596938Z 2020-01-10 00:00:50.108 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.324S (calculated from last 5 ms)
 
I 2020-01-10T00:00:50.116569292Z 2020-01-10 00:00:50.116 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:51.771910114Z 2020-01-10 00:00:51.771 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.053S (calculated from last 8 ms)
 
I 2020-01-10T00:00:51.791259232Z 2020-01-10 00:00:51.791 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:52.150054944Z 2020-01-10 00:00:52.149 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.529S (calculated from last 6 ms)
 
I 2020-01-10T00:00:52.156230906Z 2020-01-10 00:00:52.155 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:53.732936587Z 2020-01-10 00:00:53.732 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.629S (calculated from last 4 ms)
 
I 2020-01-10T00:00:53.741509301Z 2020-01-10 00:00:53.741 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:55.881690361Z 2020-01-10 00:00:55.881 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.738S (calculated from last 16 ms)
 
I 2020-01-10T00:00:55.890303851Z 2020-01-10 00:00:55.890 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:56.513733Z 2020-01-10 00:00:56.513 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.75S (calculated from last 4 ms)
 
I 2020-01-10T00:00:56.520848986Z 2020-01-10 00:00:56.520 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:57.254866332Z 2020-01-10 00:00:57.254 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.526S (calculated from last 3 ms)
 
I 2020-01-10T00:00:57.261530622Z 2020-01-10 00:00:57.261 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:00:59.130839449Z 2020-01-10 00:00:59.130 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.265S (calculated from last 6 ms)
 
I 2020-01-10T00:00:59.136957466Z 2020-01-10 00:00:59.136 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:00.251710052Z 2020-01-10 00:01:00.251 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.742S (calculated from last 2 ms)
 
I 2020-01-10T00:01:00.254785981Z 2020-01-10 00:01:00.254 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:00.593638297Z 2020-01-10 00:01:00.593 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.341S (calculated from last 11 ms)
 
I 2020-01-10T00:01:00.596095917Z 2020-01-10 00:01:00.595 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:03.938633914Z 2020-01-10 00:01:03.938 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.814S (calculated from last 6 ms)
 
I 2020-01-10T00:01:03.946906197Z 2020-01-10 00:01:03.946 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:03.958962780Z 2020-01-10 00:01:03.958 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.709S (calculated from last 12 ms)
 
I 2020-01-10T00:01:03.961631324Z 2020-01-10 00:01:03.961 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:05.206750674Z 2020-01-10 00:01:05.206 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.625S (calculated from last 13 ms)
 
I 2020-01-10T00:01:05.209695732Z 2020-01-10 00:01:05.209 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:06.677173729Z 2020-01-10 00:01:06.676 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.73S (calculated from last 10 ms)
 
I 2020-01-10T00:01:06.690305974Z 2020-01-10 00:01:06.690 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:07.214033751Z 2020-01-10 00:01:07.213 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.281S (calculated from last 10 ms)
 
I 2020-01-10T00:01:07.216851457Z 2020-01-10 00:01:07.216 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:09.458367879Z 2020-01-10 00:01:09.458 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.264S (calculated from last 9 ms)
 
I 2020-01-10T00:01:09.484144794Z 2020-01-10 00:01:09.483 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:09.753865697Z 2020-01-10 00:01:09.753 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.087S (calculated from last 9 ms)
 
I 2020-01-10T00:01:09.757017374Z 2020-01-10 00:01:09.756 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:10.940802249Z 2020-01-10 00:01:10.940 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.737S (calculated from last 5 ms)
 
I 2020-01-10T00:01:10.948768147Z 2020-01-10 00:01:10.948 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:12.646053665Z 2020-01-10 00:01:12.645 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.197S (calculated from last 1 ms)
 
I 2020-01-10T00:01:12.667457212Z 2020-01-10 00:01:12.667 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:13.850321784Z 2020-01-10 00:01:13.849 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.105S (calculated from last 5 ms)
 
I 2020-01-10T00:01:13.859548808Z 2020-01-10 00:01:13.859 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:14.389067867Z 2020-01-10 00:01:14.388 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.453S (calculated from last 4 ms)
 
I 2020-01-10T00:01:14.398481843Z 2020-01-10 00:01:14.398 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:17.094797566Z 2020-01-10 00:01:17.094 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.45S (calculated from last 8 ms)
 
I 2020-01-10T00:01:17.101736837Z 2020-01-10 00:01:17.101 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:17.375367529Z 2020-01-10 00:01:17.375 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT3.53S (calculated from last 16 ms)
 
I 2020-01-10T00:01:17.386107805Z 2020-01-10 00:01:17.385 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:18.535522195Z 2020-01-10 00:01:18.535 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.15S (calculated from last 12 ms)
 
I 2020-01-10T00:01:18.537980518Z 2020-01-10 00:01:18.537 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:20.142045058Z 2020-01-10 00:01:20.141 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT2.783S (calculated from last 10 ms)
 
I 2020-01-10T00:01:20.144286292Z 2020-01-10 00:01:20.144 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:21.418280843Z 2020-01-10 00:01:21.418 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.331S (calculated from last 6 ms)
 
I 2020-01-10T00:01:21.499874539Z 2020-01-10 00:01:21.499 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:22.610954562Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -20 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:01:22.926917967Z java.util.concurrent.TimeoutException: Request timed out after PT1M
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:132) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestWithRetry$0(AtomixClientTransportAdapter.java:61) ~[zeebe-transport-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 
I 2020-01-10T00:01:23.383478707Z 2020-01-10 00:01:23.383 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-01-09T12:06:57.978Z} in the last PT4.859S (calculated from last 12 ms)
 
I 2020-01-10T00:01:23.396678968Z 2020-01-10 00:01:23.396 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
 
I 2020-01-10T00:01:23.886354300Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -21 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-01-10T00:01:24.294480732Z java.util.concurrent.TimeoutException: Request type command-api-2 timed out in -8 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200106.173024-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
```

### PR DESCRIPTION
**Pull request by npepinpe**
**Description:**

- serializes access to `heartbeatTimer` to ensure we only set it in a single thread
- adds check to ensure we always cancel a timer before rescheduling it

**Related issues:**

closes #139, [zeebe-io/zeebe#3705](https://github.com/zeebe-io/zeebe/issues/3705)

### CODE REVIEW

**Comment by npepinpe** [comment]
I wasn't sure how to write a specific test for this race condition, if any of you has an idea let me know :+1: (I've empirically verified that this fixes [zeebe-io/zeebe#3705](https://github.com/zeebe-io/zeebe/issues/3705) by running this locally 47 times (used to fail after 2-5 times))

I added @Zelldon as a reviewer, just to have his opinion - don't feel like you have to work if you're too sick!

File: protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftContext.java [hunk 1]
```diff
@@ -727,15 +727,6 @@ public Duration getHeartbeatInterval() {
   }
 
   public ThreadContext getHeartbeatThread() {
-    // we should avoid to use to many different threads
-    // it makes sense to accept incoming requests (like heartbeats, appends etc) by one thread
-    // then we do not need to synchronize the resource access
-    // for sending we need multiple threads such that we are able to send heartbeats in time
-
```
Comment (ChrisKujawa) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftContext.java:734]: > we should avoid to use to many different threads	
    // it makes sense to accept incoming requests (like heartbeats, appends etc) by one thread	
    // then we do not need to synchronize the resource access	
    // for sending we need multiple threads such that we are able to send heartbeats in time	

I think the intention, as the comment says, was that the separate thread should only be used on leader to **send** the heartbeat. For receiving we should use one, to avoid synchronizing. But seems that we used also both on follower. I'm currently wondering if this is really necessary.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java [hunk 2]
```diff
@@ -251,49 +233,109 @@ private void resetHeartbeatTimeoutFromDifferentThread() {
...
+    final Duration pollTimeout = raft.getElectionTimeout();
+
+    if (heartbeatTimer != null && !heartbeatTimer.isDone()) {
+      log.warn(
+          "Expected no heartbeat timer to be scheduled, but one was already scheduled, cancelling it");
+      heartbeatTimer.cancel();
+    }
+
+    heartbeatTimer =
+        raft.getHeartbeatThread()
```
Comment (ChrisKujawa) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:304]: Why we need two threads for these kind of things?

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java [hunk 3]
```diff
@@ -85,14 +86,15 @@ public FollowerRole(RaftContext context) {
...
     raft.getMembershipService().removeListener(clusterListener);
-    return super.stop().thenRun(this::cancelHeartbeatTimers);
+    return super.stop().thenRun(this::cancelHeartbeatTimer);
   }
 
   /** Cancels the heartbeat timer. */
-  private void cancelHeartbeatTimers() {
-    if (heartbeatTimoutTimer != null) {
+  private void cancelHeartbeatTimer() {
+    if (heartbeatTimer != null) {
```
Comment (ChrisKujawa) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:98]: this can also be called from different threads right?

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java (hunk 2 above)
Comment (ChrisKujawa) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:304]: I assume this would make things easier if we just use the normal thread :man_shrugging:

**Review by ChrisKujawa — COMMENTED** [review]
Hey @npepinpe first of all big thanks that you found the issue :+1: But still I'm not 100% sure what the real issue was. Multiple threads was accessing some fields? For me the real change seems just setting the timer setting to null and the check whether it is done or not, right?

Would it be possible to use just one thread?

**Comment by npepinpe** [comment]
Correct, the issue is multiple threads using the same timer for different things without previously clearing it.

I'm also not sure we need the heartbeat thread on the follower...but if we use the raft thread, wouldn't we also run into the issue of a slow append on the follower causing missed heartbeats?

In the long run I'd like to challenge anyway if it was the right move to use heartbeats on a separate thread for both leader and follower (e.g. what do we gain with this over, say, swim? We dont detect all possible leader failures, just the same class that swim detects).

I think we could optimize our append on both leader and follower by sending append entries async over udp, and on the follower, we write to mmap'd files, and only flush every x requests (or 30-40ms) asynchronously (in a separate thread), where we then tell the leader our correct new index. But that's a bigger topic :sweat_smile:

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java [hunk 4]
```diff
@@ -237,8 +204,23 @@ protected VoteResponse handleVote(VoteRequest request) {
 
   @Override
   public void onLeaderHeartbeat(LeaderHeartbeatRequest request) {
+    raft.checkHeartbeatThread();
     logRequest(request);
 
+    final long currentTerm = raft.getTerm();
+    final RaftMember currentLeader = raft.getLeader();
+    if (currentLeader == null
```
Comment (deepthidevaki) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java]: We should accept the heartbeat if currentLeader == null. right?

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java (hunk 3 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:98]: Yes. We should ensure that all access to heartbeat timer is via heartbeat thread.

File: primitive/src/main/java/io/atomix/primitive/service/impl/DefaultServiceExecutor.java [hunk 5]
```diff
@@ -314,5 +314,10 @@ private synchronized void execute() {
     public synchronized void cancel() {
       scheduledTasks.remove(this);
     }
+
+    @Override
+    public synchronized boolean isDone() {
+      return scheduledTasks.contains(this);
```
Comment (deepthidevaki) [inline primitive/src/main/java/io/atomix/primitive/service/impl/DefaultServiceExecutor.java]: Did you mean `return !scheduledTasks.contains(this);` ?

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java [hunk 6]
```diff
@@ -251,49 +233,109 @@ private void resetHeartbeatTimeoutFromDifferentThread() {
...
+  private void schedulePollRequests(final Duration delay) {
+    raft.checkThread();
+
+    if (!isRunning()) {
+      return;
+    }
+
+    if (raft.getFirstCommitIndex() == 0 || raft.getState() == RaftContext.State.READY) {
+      final long missTime = System.currentTimeMillis() - lastHeartbeat;
+      log.info(
```
Comment (deepthidevaki) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:276]: Is this log necessary?

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java [hunk 7]
```diff
@@ -237,8 +204,23 @@ protected VoteResponse handleVote(VoteRequest request) {
 
   @Override
   public void onLeaderHeartbeat(LeaderHeartbeatRequest request) {
+    raft.checkHeartbeatThread();
     logRequest(request);
 
+    final long currentTerm = raft.getTerm();
+    final RaftMember currentLeader = raft.getLeader();
```
Comment (deepthidevaki) [inline protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:215]: I think there is a (rare) chance for race condition here. Heartbeat thread reading them while raft thread update. But I think it will be harmless even if it gets inconsistent values. If it happens, probably the following log reports leader mismatch wrongly.

**Review by deepthidevaki — COMMENTED** [review]
Having two threads make it more complicated. But, since we already have a separate thread for heartbeats, I am ok with the current fix. We can discuss later if we want to merge the two threads.

File: primitive/src/main/java/io/atomix/primitive/service/impl/DefaultServiceExecutor.java (hunk 5 above)
Comment (npepinpe) [reply primitive/src/main/java/io/atomix/primitive/service/impl/DefaultServiceExecutor.java]: Correct, my bad :see_no_evil:

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java (hunk 6 above)
Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:276]: It was already there; it was useful for me while trying to figure this out, and it can help explain why some elections are triggered. It shouldn't happen too often anyway because this only happens when no heartbeats are received.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java (hunk 7 above)
Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:215]: Yes, you're right, and it might cause us to reject heartbeats unnecessarily, or accept a few when we shouldn't; but assuming we receive heartbeats fairly often, it should stabilize, I think.

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java (hunk 4 above)
Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java]: True, if we have none we will just accept it as our leader anyway, so it's basically the same (assuming the term is >=).

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java (hunk 3 above)
Comment (npepinpe) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:98]: Hm, the heartbeat thread is closed only when the partition is closed, right? So it should be safe to schedule it the close there and not wait for it, I guess. :+1:

File: protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java (hunk 6 above)
Comment (deepthidevaki) [reply protocols/raft/src/main/java/io/atomix/protocols/raft/roles/FollowerRole.java:276]: :+1:

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Comment by npepinpe** [comment]
Seems `ZeebeTest` sometimes time out, I'll look into it, not sure if it's this PR or before
